/*
 *
 * Automatically generated file; DO NOT EDIT.
 * MCU App Configuration
 *
 */
#define CONFIG_C_OPTIMIZATION_LEVEL "-O0"
#define CONFIG_FLAG_USE_PRINTF_FLOAT 1
#define CONFIG_C_WARNING_SWITCH_ENUM "-Wswitch-enum"
#define CONFIG_C_DEBUG_LEVEL "-g3"
#define CONFIG_FLAG_C_STACK_USAGE 1
#define CONFIG_C_DEBUG_LEVEL_3 1
#define CONFIG_FLAG_C_DATA_SECTIONS 1
#define CONFIG_FLAG_C_WARNING_EXTRA 1
#define CONFIG_C_WARNING_ALL "-Wall"
#define CONFIG_C_DATA_SECTIONS "-fdata-sections"
#define CONFIG_USE_PRINTF_FLOAT "-u_printf_float"
#define CONFIG_FLAG_C_WARNING_SWITCH_ENUM 1
#define CONFIG_FREERTOS_TICK_RATE_HZ 1000
#define CONFIG_C_FUNCTION_SECTIONS "-ffunction-sections"
#define CONFIG_FLAG_C_WARNING_ALL 1
#define CONFIG_STD_C11 1
#define CONFIG_C_WARNING_EXTRA "-Wextra"
#define CONFIG_FLAG_C_WARNING_NO_UNUSED_PARAMETER 1
#define CONFIG_C_LANGUAGE_STANDARD "c11"
#define CONFIG_C_WARNING_NO_UNUSED_PARAMETER "-Wno-unused-parameter"
#define CONFIG_C_OPTIMIZATION_LEVEL_0 1
#define CONFIG_FLAG_C_FUNCTION_SECTIONS 1
#define CONFIG_C_STACK_USAGE "-fstack-usage"
#define CONFIG_APP_BLINK_LED_DELAY 500
